# Generated by Django 4.2.7 on 2025-03-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options_task_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
    ]
